### ISSUE TITLE
Add Support/Documentation for infinite streams

### ISSUE THREAD

**Issue by barakber** [Pebaz/Chemical#1]
Hey, love this package! thank you! 🙏 
I was looking for a way to support infinite (or very large) streams - from a database for example

#### Issue
this -
~~~ python
import itertools
it(itertools.repeat(5)).skip(10).inspect(print).go()
~~~
fails here - https://github.com/Pebaz/Chemical/blob/d7db53cf805c0c132cf8813a3a6e1813c0c2da5d/chemical/iterators.py#L29

#### A solution (hack?)
~~~ python
it(itertools.repeat(5), reverse_seed=itertools.repeat(0)).skip(10).inspect(print).go()
~~~

I was wandering if this is supported in some other way
if not - IMO it would be a great feature

**Comment by Pebaz** [comment]
Hi @barakber thanks for the kind words! 😀

This is actually the correct solution because infinite iterators are not reversible. If you try:

```python
reversed(itertools.repeat(5))
```

It throws an exception saying it isn’t reversible. That’s why I had to provide an escape hatch for non reversible iterators because some can be reversed with prior knowledge by the user and some don’t need to be reversed.

It’s possible there’s a better solution for the library though 🤷‍♂️
